runtime: nodejs22

handlers:
  # 1. Serve static files from the 'build/static' folder
  #    This handles all your CSS, JS, and media files.
  - url: /static
    static_dir: build/static

  # 2. Serve files from the 'build' folder root (like favicon.ico, manifest.json)
  #    This handles files that are not in the /static directory.
  - url: /(.*\.(json|ico|png|txt|jpg|svg))
    static_files: build/\1
    upload: build/(.*\.(json|ico|png|txt|jpg|svg))

  # 3. The "catch-all" handler for client-side routing.
  #    It serves the main index.html file for any request that hasn't been
  #    matched by the handlers above. This allows React Router to work.
  - url: /.*
    static_files: build/index.html
    upload: build/index.html