steps:
  # Step 1: Install all the project dependencies using npm
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build the production-ready React app (creates the 'build' folder)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Step 3: Deploy the contents of the 'build' folder to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

# Set a timeout for the build
timeout: '1600s'